In [34]:
import pandas as pd
import numpy as np
import os
import json

In [30]:
df_l = []

In [31]:
for file_name in os.listdir('./processed_data/matches/'):
    with open(os.path.join('./processed_data/matches/', file_name)) as f:
        s = json.load(f)
        df_l.append(s)

In [32]:
df = pd.DataFrame.from_records(df_l)

In [33]:
df.head()

,city,date,dl_applied,eliminator,overs,player_of_match,result,season,team1,team2,toss_decision,toss_winner,umpire1,umpire2,umpire3,venue,win_by_runs,win_by_wickets,winner
0,Chandigarh,2008-05-03,,,20,IK Pathan,,2008,Kings XI Punjab,Kolkata Knight Riders,bat,Kings XI Punjab,DJ Harper,I Shivram,,"Punjab Cricket Association Stadium, Mohali",9,,Kings XI Punjab
1,Delhi,2018-04-27,,,20,SS Iyer,,2018,Delhi Daredevils,Kolkata Knight Riders,field,Kolkata Knight Riders,C Shamshuddin,S Ravi,,Feroz Shah Kotla,55,,Delhi Daredevils
2,Port Elizabeth,2009-05-10,,,20,JP Duminy,,2009,Royal Challengers Bangalore,Mumbai Indians,bat,Mumbai Indians,BR Doctrove,BG Jerling,,St George's Park,16,,Mumbai Indians
3,Chandigarh,2019-04-01,,,20,SM Curran,,2019,Kings XI Punjab,Delhi Capitals,field,Delhi Capitals,CB Gaffaney,AK Chaudhary,,"Punjab Cricket Association IS Bindra Stadium, ...",14,,Kings XI Punjab
4,Jaipur,2019-04-20,,,20,SPD Smith,,2019,Rajasthan Royals,Mumbai Indians,field,Rajasthan Royals,YC Barde,S Ravi,,Sawai Mansingh Stadium,,5,Rajasthan Royals

In [8]:
df.to_csv('matches.csv', index=False)

In [35]:
matches=pd.read_csv('matches.csv')
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 746 entries, 0 to 745
Data columns (total 19 columns):
city               733 non-null object
date               746 non-null object
dl_applied         19 non-null object
eliminator         8 non-null object
overs              746 non-null int64
player_of_match    742 non-null object
result             12 non-null object
season             746 non-null int64
team1              746 non-null object
team2              746 non-null object
toss_decision      746 non-null object
toss_winner        746 non-null object
umpire1            745 non-null object
umpire2            745 non-null object
umpire3            2 non-null object
venue              746 non-null object
win_by_runs        336 non-null float64
win_by_wickets     398 non-null float64
winner             734 non-null object
dtypes: float64(2), int64(2), object(15)
memory usage: 110.8+ KB

In [39]:
matches[pd.isnull(matches['winner'])]
matches['winner'].fillna('Draw', inplace=True)
matches.head()

,city,date,dl_applied,eliminator,overs,player_of_match,result,season,team1,team2,toss_decision,toss_winner,umpire1,umpire2,umpire3,venue,win_by_runs,win_by_wickets,winner
0,Chandigarh,2008-05-03,NaN,NaN,20,IK Pathan,NaN,2008,Kings XI Punjab,Kolkata Knight Riders,bat,Kings XI Punjab,DJ Harper,I Shivram,NaN,"Punjab Cricket Association Stadium, Mohali",9.0,NaN,Kings XI Punjab
1,Delhi,2018-04-27,NaN,NaN,20,SS Iyer,NaN,2018,Delhi Daredevils,Kolkata Knight Riders,field,Kolkata Knight Riders,C Shamshuddin,S Ravi,NaN,Feroz Shah Kotla,55.0,NaN,Delhi Daredevils
2,Port Elizabeth,2009-05-10,NaN,NaN,20,JP Duminy,NaN,2009,Royal Challengers Bangalore,Mumbai Indians,bat,Mumbai Indians,BR Doctrove,BG Jerling,NaN,St George's Park,16.0,NaN,Mumbai Indians
3,Chandigarh,2019-04-01,NaN,NaN,20,SM Curran,NaN,2019,Kings XI Punjab,Delhi Capitals,field,Delhi Capitals,CB Gaffaney,AK Chaudhary,NaN,"Punjab Cricket Association IS Bindra Stadium, ...",14.0,NaN,Kings XI Punjab
4,Jaipur,2019-04-20,NaN,NaN,20,SPD Smith,NaN,2019,Rajasthan Royals,Mumbai Indians,field,Rajasthan Royals,YC Barde,S Ravi,NaN,Sawai Mansingh Stadium,NaN,5.0,Rajasthan Royals

In [80]:
df = pd.DataFrame(matches)

In [64]:
len(df)

746

In [83]:
matches.replace(['Mumbai Indians','Kolkata Knight Riders','Royal Challengers Bangalore','Deccan Chargers','Chennai Super Kings',
                 'Rajasthan Royals','Delhi Daredevils','Gujarat Lions','Kings XI Punjab',
                 'Sunrisers Hyderabad','Rising Pune Supergiants','Rising Pune Supergiant','Kochi Tuskers Kerala','Pune Warriors','Delhi Capitals']
                ,['MI','KKR','RCB','DC','CSK','RR','DD','GL','KXIP','SRH','RPS','RPS','KTK','PW','DCA'],inplace=True)

encode = {'team1': {'MI':1,'KKR':2,'RCB':3,'DC':4,'CSK':5,'RR':6,'DD':7,'GL':8,'KXIP':9,'SRH':10,'RPS':11,'KTK':12,'PW':13,'DCA':14},
          'team2': {'MI':1,'KKR':2,'RCB':3,'DC':4,'CSK':5,'RR':6,'DD':7,'GL':8,'KXIP':9,'SRH':10,'RPS':11,'KTK':12,'PW':13,'DCA':14},
          'toss_winner': {'MI':1,'KKR':2,'RCB':3,'DC':4,'CSK':5,'RR':6,'DD':7,'GL':8,'KXIP':9,'SRH':10,'RPS':11,'KTK':12,'PW':13,'DCA':14},
          'winner': {'MI':1,'KKR':2,'RCB':3,'DC':4,'CSK':5,'RR':6,'DD':7,'GL':8,'KXIP':9,'SRH':10,'RPS':11,'KTK':12,'PW':13,'DCA':14,'Draw':15}}
matches.replace(encode, inplace=True)
matches.head()

,city,date,dl_applied,eliminator,overs,player_of_match,result,season,team1,team2,toss_decision,toss_winner,umpire1,umpire2,umpire3,venue,win_by_runs,win_by_wickets,winner
0,Chandigarh,2008-05-03,NaN,NaN,20,IK Pathan,NaN,2008,9,2,bat,9,DJ Harper,I Shivram,NaN,"Punjab Cricket Association Stadium, Mohali",9.0,NaN,9
1,Delhi,2018-04-27,NaN,NaN,20,SS Iyer,NaN,2018,7,2,field,2,C Shamshuddin,S Ravi,NaN,Feroz Shah Kotla,55.0,NaN,7
2,Port Elizabeth,2009-05-10,NaN,NaN,20,JP Duminy,NaN,2009,3,1,bat,1,BR Doctrove,BG Jerling,NaN,St George's Park,16.0,NaN,1
3,Chandigarh,2019-04-01,NaN,NaN,20,SM Curran,NaN,2019,9,14,field,14,CB Gaffaney,AK Chaudhary,NaN,"Punjab Cricket Association IS Bindra Stadium, ...",14.0,NaN,9
4,Jaipur,2019-04-20,NaN,NaN,20,SPD Smith,NaN,2019,6,1,field,6,YC Barde,S Ravi,NaN,Sawai Mansingh Stadium,NaN,5.0,6

In [84]:
df1 = pd.DataFrame(matches)
df1

,city,date,dl_applied,eliminator,overs,player_of_match,result,season,team1,team2,toss_decision,toss_winner,umpire1,umpire2,umpire3,venue,win_by_runs,win_by_wickets,winner
0,Chandigarh,2008-05-03,NaN,NaN,20,IK Pathan,NaN,2008,9,2,bat,9,DJ Harper,I Shivram,NaN,"Punjab Cricket Association Stadium, Mohali",9.0,NaN,9
1,Delhi,2018-04-27,NaN,NaN,20,SS Iyer,NaN,2018,7,2,field,2,C Shamshuddin,S Ravi,NaN,Feroz Shah Kotla,55.0,NaN,7
2,Port Elizabeth,2009-05-10,NaN,NaN,20,JP Duminy,NaN,2009,3,1,bat,1,BR Doctrove,BG Jerling,NaN,St George's Park,16.0,NaN,1
3,Chandigarh,2019-04-01,NaN,NaN,20,SM Curran,NaN,2019,9,14,field,14,CB Gaffaney,AK Chaudhary,NaN,"Punjab Cricket Association IS Bindra Stadium, ...",14.0,NaN,9
4,Jaipur,2019-04-20,NaN,NaN,20,SPD Smith,NaN,2019,6,1,field,6,YC Barde,S Ravi,NaN,Sawai Mansingh Stadium,NaN,5.0,6
5,Delhi,2018-04-23,NaN,NaN,20,AS Rajpoot,NaN,2018,7,9,field,7,A Nand Kishore,CK Nandan,NaN,Feroz Shah Kotla,4.0,NaN,9
6,Johannesburg,2009-05-16,NaN,NaN,20,RG Sharma,NaN,2009,4,2,field,4,RE Koertzen,S Ravi,NaN,New Wanderers Stadium,NaN,6.0,4
7,East London,2009-05-01,NaN,NaN,20,JP Duminy,NaN,2009,2,1,bat,1,M Erasmus,SK Tarapore,NaN,Buffalo Park,9.0,NaN,1
8,Jaipur,2010-04-11,NaN,NaN,20,SR Tendulkar,NaN,2010,6,1,field,6,BR Doctrove,SK Tarapore,NaN,Sawai Mansingh Stadium,37.0,NaN,1
9,Jaipur,2019-04-11,NaN,NaN,20,MS Dhoni,NaN,2019,6,5,field,5,UV Gandhe,BNJ Oxenford,NaN,Sawai Mansingh Stadium,NaN,4.0,5
10,Hyderabad,2016-04-30,NaN,NaN,20,DA Warner,NaN,2016,10,3,field,3,AK Chaudhary,HDPK Dharmasena,NaN,"Rajiv Gandhi International Stadium, Uppal",15.0,NaN,10
11,Mumbai,2010-04-24,NaN,NaN,20,A Kumble,NaN,2010,3,4,bat,4,RE Koertzen,SJA Taufel,NaN,Dr DY Patil Sports Academy,NaN,9.0,3
12,Pune,2017-05-14,NaN,NaN,20,JD Unadkat,NaN,2017,11,9,field,11,AY Dandekar,A Deshmukh,NaN,Maharashtra Cricket Association Stadium,NaN,9.0,11
13,Delhi,2013-05-10,NaN,NaN,20,JD Unadkat,NaN,2013,7,3,field,7,NJ Llong,K Srinath,NaN,Feroz Shah Kotla,4.0,NaN,3
14,Rajkot,2016-04-21,NaN,NaN,20,B Kumar,NaN,2016,8,10,field,10,K Bharatan,HDPK Dharmasena,NaN,Saurashtra Cricket Association Stadium,NaN,10.0,10
15,Delhi,2017-04-15,NaN,NaN,20,CJ Anderson,NaN,2017,7,9,bat,7,YC Barde,Nitin Menon,NaN,Feroz Shah Kotla,51.0,NaN,7
16,Nagpur,2010-04-12,NaN,NaN,20,Harmeet Singh,NaN,2010,4,3,field,3,RE Koertzen,RB Tiffin,NaN,"Vidarbha Cricket Association Stadium, Jamtha",13.0,NaN,4
17,Cape Town,2009-04-19,D/L,NaN,20,DL Vettori,NaN,2009,7,9,field,7,MR Benson,SD Ranade,NaN,Newlands,NaN,10.0,7
18,Chennai,2015-05-04,NaN,NaN,20,SK Raina,NaN,2015,5,3,bat,5,C Shamshuddin,K Srinath,NaN,"MA Chidambaram Stadium, Chepauk",24.0,NaN,5
19,Mumbai,2019-04-15,NaN,NaN,20,SL Malinga,NaN,2019,1,3,field,1,M Erasmus,Nitin Menon,NaN,Wankhede Stadium,NaN,5.0,1
20,Mumbai,2012-04-16,NaN,NaN,20,S Nadeem,NaN,2012,1,7,field,7,BF Bowden,SK Tarapore,NaN,Wankhede Stadium,NaN,7.0,7
21,Mumbai,2011-04-27,NaN,NaN,20,DE Bollinger,NaN,2011,13,5,bat,13,Asad Rauf,SL Shastri,NaN,Dr DY Patil Sports Academy,NaN,8.0,5
22,Centurion,2009-05-07,D/L,NaN,20,ML Hayden,NaN,2009,5,9,bat,5,DJ Harper,TH Wijewardene,NaN,SuperSport Park,12.0,NaN,5
23,Delhi,2008-04-19,NaN,NaN,20,MF Maharoof,NaN,2008,7,6,bat,6,Aleem Dar,GA Pratapkumar,NaN,Feroz Shah Kotla,NaN,9.0,7
24,Delhi,2012-05-15,NaN,NaN,20,UT Yadav,NaN,2012,7,9,bat,9,HDPK Dharmasena,BNJ Oxenford,NaN,Feroz Shah Kotla,NaN,5.0,7
25,Mumbai,2011-04-13,NaN,NaN,20,MD Mishra,NaN,2011,13,12,bat,12,S Asnani,PR Reiffel,NaN,Dr DY Patil Sports Academy,NaN,4.0,13
26,Pune,2017-04-22,NaN,NaN,20,MS Dhoni,NaN,2017,11,10,field,11,AY Dandekar,A Deshmukh,NaN,Maharashtra Cricket Association Stadium,NaN,6.0,11
27,Kolkata,2019-04-12,NaN,NaN,20,S Dhawan,NaN,2019,2,14,field,14,YC Barde,CK Nandan,NaN,Eden Gardens,NaN,7.0,14
28,Kolkata,2011-05-22,NaN,NaN,20,JEC Franklin,NaN,2011,2,1,field,1,SK Tarapore,SJA Taufel,NaN,Eden Gardens,NaN,5.0,1
29,Delhi,2018-05-20,NaN,NaN,20,A Mishra,NaN,2018,7,1,bat,7,HDPK Dharmasena,CK Nandan,NaN,Feroz Shah Kotla,11.0,NaN,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,Delhi,2018-05-18,NaN,NaN,20,HV Patel,NaN,2018,7,5,field,5,VA Kulkarni,HDPK Dharmasena,NaN,Feroz Shah Kotla,34.0,NaN,7
717,Hyderabad,2018-05-05,NaN,NaN,20,Rashid Khan,NaN,2018,10,7,bat,7,BNJ Oxenford,CK Nandan,NaN,"Rajiv Gandhi International Stadium, Uppal",NaN,7.0,10
718,Hyderabad,2008-05-27,NaN,NaN,20,SK Raina,NaN,2008,4,5,bat,4,BG Jerling,AM Saheba,NaN,"Rajiv Gandhi International Stadium, Uppal",NaN,7.0,5
719,Kolkata,2015-04-08,NaN,NaN,20,M Morkel,NaN,2015,2,1,field,2,S Ravi,C Shamshuddin,NaN,Eden Gardens,NaN,7.0,2
720,Hyderabad,2017-05-06,NaN,NaN,20,JD Unadkat,NaN,2017,10,11,field,10,KN Ananthapadmanabhan,AK Chaudhary,NaN,"Rajiv Gandhi International Stadium, Uppal",12.0,NaN,11
721,Chandigarh,2013-04-10,NaN,NaN,20,MEK Hussey,NaN,2013,9,5,field,5,Aleem Dar,C Shamshuddin,NaN,"Punjab Cricket Association Stadium, Mohali",NaN,10.0,5
722,Pune,2012-04-08,NaN,NaN,20,MN Samuels,NaN,2012,13,9,bat,13,S Das,SJA Taufel,NaN,Subrata Roy Sahara Stadium,22.0,NaN,13
723,Chandigarh,2008-05-12,NaN,NaN,20,SE Marsh,NaN,2008,9,3,bat,3,BR Doctrove,I Shivram,NaN,"Punjab Cricket Association Stadium, Mohali",NaN,9.0,9
724,Hyderabad,2008-04-22,NaN,NaN,20,V Sehwag,NaN,2008,4,7,bat,4,IL Howell,AM Saheba,NaN,"Rajiv Gandhi International Stadium, Uppal",NaN,9.0,7
725,Hyderabad,2013-04-07,NaN,SRH,20,GH Vihari,tie,2013,10,3,bat,3,AK Chaudhary,S Ravi,NaN,"Rajiv Gandhi International Stadium, Uppal",NaN,NaN,14
726,Abu Dhabi,2014-04-26,NaN,NaN,20,Sandeep Sharma,NaN,2014,2,9,field,2,HDPK Dharmasena,RK Illingworth,NaN,Sheikh Zayed Stadium,23.0,NaN,9
727,Hyderabad,2014-05-14,NaN,NaN,20,WP Saha,NaN,2014,10,9,field,9,VA Kulkarni,PG Pathak,NaN,"Rajiv Gandhi International Stadium, Uppal",NaN,6.0,9
728,Bangalore,2015-05-17,NaN,NaN,20,NaN,no result,2015,3,7,field,3,HDPK Dharmasena,K Srinivasan,NaN,M Chinnaswamy Stadium,NaN,NaN,14
729,Hyderabad,2017-04-09,NaN,NaN,20,Rashid Khan,NaN,2017,10,8,field,10,A Deshmukh,NJ Llong,NaN,"Rajiv Gandhi International Stadium, Uppal",NaN,9.0,10
730,Kanpur,2017-05-10,NaN,NaN,20,SS Iyer,NaN,2017,8,7,field,7,YC Barde,AK Chaudhary,NaN,Green Park,NaN,2.0,7
731,Kochi,2011-04-30,NaN,NaN,20,V Sehwag,NaN,2011,12,7,bat,7,HDPK Dharmasena,AL Hill,NaN,Nehru Stadium,38.0,NaN,7
732,NaN,2014-04-17,NaN,NaN,20,YS Chahal,NaN,2014,7,3,field,3,Aleem Dar,S Ravi,NaN,Sharjah Cricket Stadium,NaN,8.0,3
733,Kolkata,2011-05-07,D/L,NaN,20,Iqbal Abdulla,NaN,2011,2,5,bat,5,Asad Rauf,PR Reiffel,NaN,Eden Gardens,10.0,NaN,2
734,Delhi,2015-04-23,NaN,NaN,20,SS Iyer,NaN,2015,7,1,field,1,SD Fry,CK Nandan,NaN,Feroz Shah Kotla,37.0,NaN,7
735,Chandigarh,2013-05-06,NaN,NaN,20,DA Miller,NaN,2013,9,3,field,9,VA Kulkarni,NJ Llong,NaN,"Punjab Cricket Association Stadium, Mohali",NaN,6.0,9
736,Jaipur,2018-05-08,NaN,NaN,20,JC Buttler,NaN,2018,6,9,bat,6,M Erasmus,Nitin Menon,NaN,Sawai Mansingh Stadium,15.0,NaN,6
737,Mumbai,2017-04-09,NaN,NaN,20,N Rana,NaN,2017,1,2,field,1,Nitin Menon,CK Nandan,NaN,Wankhede Stadium,NaN,4.0,1
738,Mumbai,2019-03-24,NaN,NaN,20,RR Pant,NaN,2019,1,14,field,1,YC Barde,S Ravi,NaN,Wankhede Stadium,37.0,NaN,14
739,Dharamsala,2012-05-17,NaN,NaN,20,AC Gilchrist,NaN,2012,9,5,field,9,VA Kulkarni,SK Tarapore,NaN,Himachal Pradesh Cricket Association Stadium,NaN,6.0,9
740,Ranchi,2015-05-22,NaN,NaN,20,A Nehra,NaN,2015,5,3,field,5,AK Chaudhary,CB Gaffaney,NaN,JSCA International Stadium Complex,NaN,3.0,5
741,Bangalore,2012-04-07,NaN,NaN,20,AB de Villiers,NaN,2012,3,7,field,7,S Asnani,S Ravi,NaN,M Chinnaswamy Stadium,20.0,NaN,3
742,Chennai,2011-05-01,NaN,NaN,20,JA Morkel,NaN,2011,5,4,bat,5,Aleem Dar,RB Tiffin,NaN,"MA Chidambaram Stadium, Chepauk",19.0,NaN,5
743,Rajkot,2017-04-23,NaN,NaN,20,HM Amla,NaN,2017,8,9,field,8,AK Chaudhary,M Erasmus,NaN,Saurashtra Cricket Association Stadium,26.0,NaN,9
744,Delhi,2012-05-07,NaN,NaN,20,JH Kallis,NaN,2012,7,2,bat,7,JD Cloete,S Ravi,NaN,Feroz Shah Kotla,NaN,6.0,2
745,Pune,2013-05-11,NaN,NaN,20,MG Johnson,NaN,2013,13,1,bat,13,Asad Rauf,AK Chaudhary,NaN,Subrata Roy Sahara Stadium,NaN,5.0,1

In [86]:
dicVal = encode['winner']
temp1=df1['toss_winner'].value_counts(sort=True)
temp2=df1['winner'].value_counts(sort=True)
print('No of toss winners by each team')
for idx, val in temp1.iteritems():
   print('{} -> {}'.format(list(dicVal.keys())[list(dicVal.values()).index(idx)],val))

No of toss winners by each team
MI -> 95
KKR -> 91
CSK -> 87
KXIP -> 80
DD -> 80
RCB -> 80
RR -> 79
SRH -> 46
DC -> 43
PW -> 20
GL -> 15
RPS -> 13
DCA -> 9
KTK -> 8

In [87]:
print('No of match winners by each team')
for idx, val in temp2.iteritems():
   print('{} -> {}'.format(list(dicVal.keys())[list(dicVal.values()).index(idx)],val))

No of match winners by each team
MI -> 104
CSK -> 99
KKR -> 91
RCB -> 82
KXIP -> 79
RR -> 73
DD -> 67
SRH -> 57
DC -> 29
DCA -> 19
RPS -> 15
GL -> 13
PW -> 12
KTK -> 6

In [88]:
df3 = df1[['team1','team2']]
df3

     team1  team2
0        9      2
1        7      2
2        3      1
3        9     14
4        6      1
5        7      9
6        4      2
7        2      1
8        6      1
9        6      5
10      10      3
11       3      4
12      11      9
13       7      3
14       8     10
15       7      9
16       4      3
17       7      9
18       5      3
19       1      3
20       1      7
21      13      5
22       5      9
23       7      6
24       7      9
25      13     12
26      11     10
27       2     14
28       2      1
29       7      1
..     ...    ...
716      7      5
717     10      7
718      4      5
719      2      1
720     10     11
721      9      5
722     13      9
723      9      3
724      4      7
725     10      3
726      2      9
727     10      9
728      3      7
729     10      8
730      8      7
731     12      7
732      7      3
733      2      5
734      7      1
735      9      3
736      6      9
737      1      2
738      1     14
739      9      5
740      5      3
741      3      7
742      5      4
743      8      9
744      7      2
745     13      1

[746 rows x 2 columns]

In [89]:
df4 = df1['winner']
df4

0       9
1       7
2       1
3       9
4       6
5       9
6       4
7       1
8       1
9       5
10     10
11      3
12     11
13      3
14     10
15      7
16      4
17      7
18      5
19      1
20      7
21      5
22      5
23      7
24      7
25     13
26     11
27     14
28      1
29      7
       ..
716     7
717    10
718     5
719     2
720    11
721     5
722    13
723     9
724     7
725    14
726     9
727     9
728    14
729    10
730     7
731     7
732     3
733     2
734     7
735     9
736     6
737     1
738    14
739     9
740     5
741     3
742     5
743     9
744     2
745     1
Name: winner, Length: 746, dtype: int64

In [99]:
df5 = df3[~df3.isin(df4)]
df5

     team1  team2
0      NaN    2.0
1      NaN    2.0
2      3.0    NaN
3      NaN   14.0
4      NaN    1.0
5      7.0    NaN
6      NaN    2.0
7      2.0    NaN
8      6.0    NaN
9      6.0    NaN
10     NaN    3.0
11     NaN    4.0
12     NaN    9.0
13     7.0    NaN
14     8.0    NaN
15     NaN    9.0
16     NaN    3.0
17     NaN    9.0
18     NaN    3.0
19     NaN    3.0
20     1.0    NaN
21    13.0    NaN
22     NaN    9.0
23     NaN    6.0
24     NaN    9.0
25     NaN   12.0
26     NaN   10.0
27     2.0    NaN
28     2.0    NaN
29     NaN    1.0
..     ...    ...
716    NaN    5.0
717    NaN    7.0
718    4.0    NaN
719    NaN    1.0
720   10.0    NaN
721    9.0    NaN
722    NaN    9.0
723    NaN    3.0
724    4.0    NaN
725   10.0    3.0
726    2.0    NaN
727   10.0    NaN
728    3.0    7.0
729    NaN    8.0
730    8.0    NaN
731   12.0    NaN
732    7.0    NaN
733    NaN    5.0
734    NaN    1.0
735    NaN    3.0
736    NaN    9.0
737    NaN    2.0
738    1.0    NaN
739    NaN    5.0
740    NaN    3.0
741    NaN    7.0
742    NaN    4.0
743    8.0    NaN
744    7.0    NaN
745   13.0    NaN

[746 rows x 2 columns]

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "Series"